### PR TITLE
Integration tests and Global exception handling 

### LINKED ISSUE #24: Global Exception handling
Add global exception handling to get better structured error response

### PR DESCRIPTION
**Pull request by SabuhiYusif**
resolves #24 
Also adds integration tests for creation boards

### CODE REVIEW

File: src/main/resources/db/migration/V0__initial_version.sql [hunk 1]
```diff
@@ -12,14 +12,14 @@ CREATE TABLE tasker.board_columns
...
+    board_id uuid REFERENCES tasker.boards (id) ON DELETE CASCADE
 );
 
 CREATE TABLE tasker.cards
 (
     id          uuid PRIMARY KEY,
-    column_id   uuid REFERENCES board_columns (id) ON DELETE CASCADE,
-    board_id    uuid REFERENCES boards (id) ON DELETE CASCADE,
+    column_id   uuid REFERENCES tasker.board_columns (id) ON DELETE CASCADE,
+    board_id    uuid REFERENCES tasker.boards (id) ON DELETE CASCADE,
```
Comment (SabuhiYusif) [inline src/main/resources/db/migration/V0__initial_version.sql:22]: this is because test env didn't like just boards :P

File: src/main/java/com/tasker/server/rest/GlobalExceptionHandler.java [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+import org.springframework.web.bind.MethodArgumentNotValidException;
+import org.springframework.web.bind.annotation.RestControllerAdvice;
+import org.springframework.web.context.request.WebRequest;
+import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;
+
+import java.util.HashMap;
+import java.util.Map;
+
+@RestControllerAdvice
+public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
```
Comment (javidy) [inline src/main/java/com/tasker/server/rest/GlobalExceptionHandler.java:16]: given that GlobalExceptionHandler class is under this path src/main/java/com/tasker/server/rest, will it be available for boards rest controllers which is under this path ? src/main/java/com/tasker/server/boards/rest/

Comment (SabuhiYusif) [reply src/main/java/com/tasker/server/rest/GlobalExceptionHandler.java:16]: Yes
